version: '3'

services:
  db:
    image: postgres
  web:
    image: lern:v2
    volumes:
      - mylund:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  # mysql:
  #   image: mysql:5.7.22
  #   container_name: spa_mysql
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_USER: root
  #     MYSQL_ROOT_PASSWORD: 111
  #     MYSQL_DATABASE: spa_app
  #   ports:
  #     - "3307:3306"

volumes:
  mylund:
